
from flask import url_for, Flask
from markupsafe import escape

app = Flask(__name__)

@app.route('/')
def index():
	return 'index'

@app.route('/login/')
def login():
	return 'login'

@app.route('/user/<name>')
def profile(name):
	return f'hello {escape(name)}'

with app.test_request_context():

	print(f'url of index :  { url_for("index") } ')

	print(f'url of login :  {url_for("login")}')

	print(f"url of login next='/' :  {url_for('login',next='/')} ")

	print(f"url of profile :  {url_for('profile', name='anil')}")
	print(url_for('index'))



#  URL Building
# Using url_for() to build URLs makes your code more descriptive and self-explanatory. insted of having raw url , we have named routes that indicate the each url.
# The URLs generated by url_for() are always absolute, meaning they include the full path from the root of the website (e.g., 'https://example.com/')

# The output of the print statements with url_for() in your code snippet will not be visible in a web page or on a specific URL path.
# Instead, these print statements will generate output in your application's server logs or in your console 
